# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'ramakrishnambdocker/WebAppDockerDemoInVS2019:$(build.buildNumber)'

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    command: Build an image
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: DockerRegistryRK
    dockerFile: Dockerfile
    imageName: $(imageName)
    restartPolicy: always
    
    
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: Push an image
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: DockerRegistryRK
    dockerFile: Dockerfile
    imageName: $(imageName)
    restartPolicy: always